import turtle

turtle_bank=turtle.Turtle()
turtle_pillars=turtle.Turtle()
turtle_door=turtle.Turtle()
turtle_flower1=turtle.Turtle()
turtle_flower2=turtle.Turtle()

turtle_bank.hideturtle()
turtle_pillars.hideturtle()
turtle_door.hideturtle()
turtle_flower1.hideturtle()
turtle_flower2.hideturtle()

turtle_bank.penup()
turtle_pillars.penup()
turtle_door.penup()
turtle_flower1.penup()
turtle_flower2.penup()

turtle_bank.color("darkgreen")
turtle_pillars.color("green")
turtle_door.color("brown")
turtle_flower1.color("pink")
turtle_flower2.color("pink")

turtle_bank.goto(-100,100)
turtle_pillars.goto(-90,70)
turtle_door.goto(-20,-100)
turtle_flower1.goto(-200,50)
turtle_flower2.goto(250,50)

turtle_bank.pensize(3)
turtle_bank.showturtle()
turtle_bank.pendown()
turtle_bank.goto(100,100)
turtle_bank.goto(100,-100)
turtle_bank.goto(-100,-100)
turtle_bank.goto(-100,100)
turtle_bank.penup()
turtle_bank.goto(100,70)
turtle_bank.pendown()
turtle_bank.goto(-100,70)
turtle_bank.penup()
turtle_bank.goto(-27,80)
turtle_bank.pendown()
turtle_bank.write("ჭანა ექსპრესი")
turtle_bank.hideturtle()

turtle_pillars.pensize(2)
turtle_pillars.showturtle()
turtle_pillars.pendown()
turtle_pillars.goto(-90,-100)
turtle_pillars.penup()
turtle_pillars.goto(-70,70)
turtle_pillars.pendown()
turtle_pillars.goto(-70,-100)
turtle_pillars.penup()
turtle_pillars.goto(-50,70)
turtle_pillars.pendown()
turtle_pillars.goto(-50,-100)
turtle_pillars.penup()
turtle_pillars.goto(-30,70)
turtle_pillars.pendown()
turtle_pillars.goto(-30,-100)
turtle_pillars.penup()
turtle_pillars.goto(30,70)
turtle_pillars.pendown()
turtle_pillars.goto(30,-100)
turtle_pillars.penup()
turtle_pillars.goto(50,70)
turtle_pillars.pendown()
turtle_pillars.goto(50,-100)
turtle_pillars.penup()
turtle_pillars.goto(70,70)
turtle_pillars.pendown()
turtle_pillars.goto(70,-100)
turtle_pillars.penup()
turtle_pillars.goto(90,70)
turtle_pillars.pendown()
turtle_pillars.goto(90,-100)
turtle_pillars.hideturtle()

turtle_door.pensize(2)
turtle_door.showturtle()
turtle_door.pendown()
turtle_door.goto(-20,-20)
turtle_door.goto(20,-20)
turtle_door.goto(20,-100)
turtle_door.penup()
turtle_door.hideturtle()

turtle_flower1.pensize(2)
turtle_flower1.right(108)
turtle_flower1.showturtle()
turtle_flower1.pendown()
count=int(0)
while count<6:
    turtle_flower1.forward(30)
    turtle_flower1.right(72)
    count=count+1
# turtle_flower1.goto(-250,50)
# turtle_flower1.goto(-250,25)
# turtle_flower1.goto(-300,25)
# turtle_flower1.goto(-300,50)
turtle_flower1.penup()
turtle_flower1.pensize(1)
turtle_flower1.goto(-225,20)
turtle_flower1.pendown()
turtle_flower1.color("green")
turtle_flower1.goto(-225,-50)
turtle_flower1.hideturtle()

turtle_flower2.pensize(2)
turtle_flower2.right(108)
turtle_flower2.showturtle()
turtle_flower2.pendown()
countt=int(0)
while countt<6:
    turtle_flower2.forward(30)
    turtle_flower2.right(72)
    countt=countt+1
# turtle_flower2.goto(250,50)
# turtle_flower2.goto(250,25)
# turtle_flower2.goto(300,25)
# turtle_flower2.goto(300,50)
turtle_flower2.penup()
turtle_flower2.pensize(1)
turtle_flower2.goto(225,20)
turtle_flower2.pendown()
turtle_flower2.color("green")
turtle_flower2.goto(225,-50)
turtle_flower2.hideturtle()

turtle.exitonclick()